# Generated by Django 3.2.9 on 2023-08-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Models_data',
        ),
    ]
